services:
  # Node.js Express API service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ansiblenode-api
    environment:
      PORT: 8000
      CONNECTION_STRING: mongodb://pedromoreira:1080@192.168.0.113:27017/admin
    ports:
      - '8000:8000'
